project_name: SteamGuardDog
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
    format_overrides:
      - goos: windows
        format: zip
    files:
      - "*.md"
      - "LICENSE"
      - "*.json"